### PR TITLE
❇️ Health check point added

### PR DESCRIPTION
**Pull request by shuhaib-aot**
http://localhost:3001/checkpoint

### CODE REVIEW

**Review by abhilash-aot — APPROVED** [review]
@sreehari-aot  check any updation needed for form checkpoint response or endpoint name

**Comment by sreehari-aot** [comment]
> @sreehari-aot check any updation needed for form checkpoint response or endpoint name

The checkpoint should confirm the database is up and running before responding back

**Comment by shuhaib-aot** [comment]
> > @sreehari-aot check any updation needed for form checkpoint response or endpoint name
> 
> The checkpoint should confirm the database is up and running before responding back

yes after DB config it will work

**Comment by sreehari-aot** [comment]
> > > @sreehari-aot check any updation needed for form checkpoint response or endpoint name
> > 
> > 
> > The checkpoint should confirm the database is up and running before responding back
> 
> yes after DB config it will work

You can run a sample get query for the checkpoint endpoint. Similar implementation for the admin API 
https://github.com/AOT-Technologies/forms-flow-ai-admin/blob/develop/admin_api/resources/ops.py

**Pull request closed without merging**
